[build]
  base = "har-xapp-website"
  command = "npm run build:netlify"
  publish = "out"

[build.environment]
  NETLIFY = "true"
  NODE_VERSION = "20"
  NEXT_TELEMETRY_DISABLED = "1"
  DISABLE_ESLINT_PLUGIN = "true"
  
[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.processing]
  skip_processing = true

[build.processing.css]
  bundle = false
  minify = false

[build.processing.js]
  bundle = false
  minify = false

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = false 