[build]
  base = "har-xapp-website"
  command = "npm run build:netlify"
  publish = "out"

[build.environment]
  NETLIFY = "true"
  NODE_VERSION = "18.18.0"
  NEXT_TELEMETRY_DISABLED = "1"
  DISABLE_ESLINT_PLUGIN = "true"
  SKIP_ESLINT_CHECK = "true"
  # Netlify'ın Yarn kullanmasını engellemek için
  NETLIFY_USE_YARN = "false"
  NPM_FLAGS = "--no-package-lock --legacy-peer-deps"
  CI = "false"

# Next.js projeleri için özel plugin
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Build öncesi yapılması gerekenler (basitleştirildi)
[build.lifecycle]
  onBuild = "echo 'Starting Next.js build...'"

# Redirect ayarları
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  conditions = {Language = ["tr"]}

[[redirects]]
  from = "/_next/static/*"
  to = "/static/:splat"
  status = 301
  force = true

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[build.processing]
  skip_processing = true

[build.processing.css]
  bundle = false
  minify = false

[build.processing.js]
  bundle = false
  minify = false

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = false 