[build]
  base = "har-xapp-website"
  command = "npm run build"
  publish = "out"

[build.environment]
  NETLIFY = "true"
  NODE_VERSION = "18.18.0"
  NEXT_TELEMETRY_DISABLED = "1"
  DISABLE_ESLINT_PLUGIN = "true"
  NPM_FLAGS = "--no-optional --legacy-peer-deps"

# Teşekkürler sayfaları için özel yönlendirmeler
[[redirects]]
  from = "/demo-talep/tesekkurler"
  to = "/demo-talep"
  status = 301

[[redirects]]
  from = "/iletisim/tesekkurler"
  to = "/iletisim"
  status = 301

# Genel yönlendirme
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Next.js projeleri için özel plugin
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Build öncesi yapılması gerekenler (basitleştirildi)
[build.lifecycle]
  onBuild = "echo 'Starting Next.js build...'"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[build.processing]
  skip_processing = true

[build.processing.css]
  bundle = false
  minify = false

[build.processing.js]
  bundle = false
  minify = false

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = false 