[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NETLIFY = "true"
  NODE_VERSION = "18.18.0"
  NEXT_TELEMETRY_DISABLED = "1"
  DISABLE_ESLINT_PLUGIN = "true"
  NPM_FLAGS = "--no-optional --legacy-peer-deps --no-engine-strict"
  ENGINE_STRICT = "false"

# Cache-Control headerları
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# SPA yönlendirmeleri
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  conditions = {Language = [], Role = []}

# Teşekkürler sayfaları için özel yönlendirmeler
[[redirects]]
  from = "/demo-talep/tesekkurler"
  to = "/demo-talep"
  status = 301

[[redirects]]
  from = "/iletisim/tesekkurler"
  to = "/iletisim"
  status = 301

# Next.js projeleri için özel plugin
[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[build.processing]
  skip_processing = true

[build.processing.css]
  bundle = false
  minify = false

[build.processing.js]
  bundle = false
  minify = false

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = false 